import type { Metadata } from "next";
import {
  RedactionRegular,
  RedactionBold,
  RedactionItalic,
  W95,
} from "@/utils/get_fonts";
import "../../globals.css";
import FollowHeader from "@/components/headers/follow-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${W95.variable} ${RedactionRegular.variable} ${RedactionBold.variable} ${RedactionItalic.variable}`}
    >
      <body>
        <FollowHeader />
        <div className="px-2 h-full w-full">{children}</div>
      </body>
    </html>
  );
}
