import type { Metadata } from "next";
import "../../globals.css";
import GeneralHeader from "@/components/headers/general-header";
import {
  RedactionRegular,
  RedactionBold,
  RedactionItalic,
  W95,
} from "@/utils/get_fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerItems: HeaderItem[] = [
    { text: "Pelilauta", href: "/board" },
    { text: "Laudat", href: "/boards" },
    { text: "Juomat", href: "/drinks" },
  ];
  return (
    <html
      lang="en"
      className={`${W95.variable} ${RedactionRegular.variable} ${RedactionBold.variable} ${RedactionItalic.variable}`}
    >
      <body>
        <GeneralHeader base_path="/admin" items={headerItems} />
        <div className="p-2 h-[90dvh] min-h-0">{children}</div>
      </body>
    </html>
  );
}
