services:
  web:
    build:
      context: .
      target: runner
    env_file:
      - .env.development
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped
