import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "@tietokilta/ui/global.css";
import "../../globals.css";
import Header from "@/components/headers/general-header";
import {HeaderItem} from "@/utils/types";
import GeneralHeader from "@/components/headers/general-header";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let headerItems: HeaderItem[] = [
    { text: "Pelilauta", href: "/board" },
    { text: "Laudat", href: "/boards" },
    { text: "Juomat", href: "/drinks"}]
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased font-[family-name:var(--font-geist-sans)]`}
      >
        <GeneralHeader base_path="/secretary" items={headerItems} />
        <div className="p-2">
          {children}
        </div>
      </body>
    </html>
  );
}
