import type { Metadata } from "next";
import {
  RedactionRegular,
  RedactionBold,
  RedactionItalic,
  W95,
} from "@/utils/get_fonts";
import "@tietokilta/ui/global.css";
import "../../globals.css";
import { HeaderItem } from "@/utils/types";
import GeneralHeader from "@/components/headers/general-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerItems: HeaderItem[] = [
    { text: "Pelilauta", href: "/board" },
    { text: "Laudat", href: "/boards" },
    { text: "Juomat", href: "/drinks" },
  ];
  return (
    <html
      lang="fi"
      className={`${W95.variable} ${RedactionRegular.variable} ${RedactionBold.variable} ${RedactionItalic.variable}`}
    >
      <body>
        <GeneralHeader base_path="/team" items={headerItems} />
        <div className="p-2">{children}</div>
      </body>
    </html>
  );
}
