import type { Metadata } from "next";
import {
  RedactionRegular,
  RedactionBold,
  RedactionItalic,
  W95,
} from "@/utils/get_fonts";
import "@tietokilta/ui/global.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${W95.variable} ${RedactionRegular.variable} ${RedactionBold.variable} ${RedactionItalic.variable}`}
    >
      <body>
        <div className="flex flex-col h-screen overflow-hidden">{children}</div>
      </body>
    </html>
  );
}
