import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "@tietokilta/ui/global.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased font-[family-name:var(--font-geist-sans)]`}
      >
        <div className="flec flex-col p-2 h-screen overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
